/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      spacing: {
        // 整体间距缩小约15%
        '1': '0.22rem',
        '2': '0.43rem',
        '3': '0.64rem',
        '4': '0.85rem',
        '5': '1.06rem',
        '6': '1.28rem',
        '8': '1.7rem',
        '10': '2.13rem',
        '12': '2.55rem',
        '16': '3.4rem',
        '20': '4.25rem',
        '24': '5.1rem',
      },
      fontSize: {
        // 字体大小整体缩小
        'xs': ['0.7rem', { lineHeight: '1rem' }],
        'sm': ['0.8rem', { lineHeight: '1.15rem' }],
        'base': ['0.9rem', { lineHeight: '1.35rem' }],
        'lg': ['1rem', { lineHeight: '1.5rem' }],
        'xl': ['1.15rem', { lineHeight: '1.65rem' }],
        '2xl': ['1.35rem', { lineHeight: '1.85rem' }],
        '3xl': ['1.7rem', { lineHeight: '2.15rem' }],
        '4xl': ['2rem', { lineHeight: '2.35rem' }],
      },
      colors: {
        "tertiary-fixed": "#ffdcbc",
        "secondary-container": "#7cf8d9",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed": "#2c1700",
        "tertiary-container": "#532f00",
        "on-surface-variant": "#41484b",
        "on-error": "#ffffff",
        "tertiary": "#351c00",
        "primary-fixed-dim": "#9ecee1",
        "primary-container": "#003d4d",
        "primary": "#002631",
        "surface-container-high": "#e7e8e9",
        "outline-variant": "#c0c8cc",
        "on-primary-fixed": "#001f28",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#00725e",
        "error": "#ba1a1a",
        "primary-fixed": "#baeafe",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#194d5d",
        "on-secondary-fixed-variant": "#005142",
        "inverse-on-surface": "#f0f1f2",
        "surface-bright": "#f8f9fa",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-primary": "#ffffff",
        "inverse-primary": "#9ecee1",
        "on-surface": "#191c1d",
        "on-primary-container": "#79a8ba",
        "outline": "#71787c",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "on-secondary": "#ffffff",
        "secondary": "#00382e",
        "on-tertiary": "#ffffff",
        "on-error-container": "#410002",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "on-tertiary-container": "#ffdcbc",
        "secondary-fixed": "#7cf8d9",
        "on-secondary-fixed": "#00201a",
        "secondary-fixed-dim": "#5fdbbd",
        "scrim": "#000000",
      },
      fontFamily: {
        'manrope': ['Manrope', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
