"""LLM service module for LabManager Python backend.

This module provides LLM integration for generating AI-powered recommendations,
report narratives, and retrospective suggestions. It mirrors the TypeScript
implementation in backend/src/services/llm-service.ts.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import httpx


@dataclass
class LLMRecommendation:
    """Recommendation generated by LLM for an AI event."""

    reason: str
    risk_summary: str
    action_summary: str
    meta: dict[str, Any]


@dataclass
class LLMReportNarrative:
    """Narrative generated by LLM for a report."""

    summary: str
    highlights: list[str]
    meta: dict[str, Any]


class LLMService(ABC):
    """Abstract base class for LLM services."""

    @abstractmethod
    async def generate_recommendation(
        self, event: dict[str, Any], context: dict[str, Any]
    ) -> LLMRecommendation:
        """Generate task recommendation for an AI event.

        Args:
            event: The normalized AI event
            context: Additional context (handler result, task draft, etc.)

        Returns:
            LLMRecommendation with reason, risk summary, and action summary
        """

    @abstractmethod
    async def generate_report_narrative(
        self, report_data: dict[str, Any]
    ) -> LLMReportNarrative:
        """Generate narrative summary for a report.

        Args:
            report_data: Report statistics and metadata

        Returns:
            LLMReportNarrative with summary and highlights
        """

    @abstractmethod
    async def generate_suggestions(
        self, retrospective_data: dict[str, Any]
    ) -> list[str]:
        """Generate strategy optimization suggestions from retrospective data.

        Args:
            retrospective_data: Patterns and analysis from task execution history

        Returns:
            List of actionable suggestions
        """


class OpenAICompatibleLLMService(LLMService):
    """LLM service implementation using OpenAI-compatible API.

    This service can work with OpenAI API or any compatible endpoint
    (e.g., local LLM servers, Azure OpenAI, etc.).
    """

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.openai.com/v1",
        model: str = "gpt-4o-mini",
        timeout: int = 20,
    ):
        """Initialize the OpenAI-compatible LLM service.

        Args:
            api_key: API key for authentication
            base_url: Base URL for the API endpoint
            model: Model name to use
            timeout: Request timeout in seconds
        """
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout = timeout
        self.client = httpx.AsyncClient(timeout=timeout)

    async def _call_api(
        self,
        messages: list[dict[str, str]],
        response_format: str = "json_object",
    ) -> dict[str, Any]:
        """Call the OpenAI-compatible API.

        Args:
            messages: List of message dicts with role and content
            response_format: Response format type (json_object or text)

        Returns:
            Parsed response from the API

        Raises:
            httpx.HTTPError: If the API request fails
        """
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        payload: dict[str, Any] = {
            "model": self.model,
            "messages": messages,
        }

        if response_format == "json_object":
            payload["response_format"] = {"type": "json_object"}

        response = await self.client.post(
            f"{self.base_url}/chat/completions",
            headers=headers,
            json=payload,
        )
        response.raise_for_status()

        result = response.json()
        content = result["choices"][0]["message"]["content"]

        if response_format == "json_object":
            return json.loads(content)
        return {"text": content}

    async def generate_recommendation(
        self, event: dict[str, Any], context: dict[str, Any]
    ) -> LLMRecommendation:
        """Generate task recommendation using LLM."""
        event_type = event.get("type", "unknown")
        source_name = event.get("sourceName", "Unknown")
        priority = event.get("priority", "medium")
        risk_level = event.get("riskLevel", "medium")

        prompt = f"""你是实验室管理系统的 AI 助手。请为以下事件生成任务推荐：

事件类型: {event_type}
来源: {source_name}
优先级: {priority}
风险级别: {risk_level}
摘要: {event.get("summary", "")}

请提供 JSON 格式的响应，包含：
- reason: 为什么需要这个任务（2-3 句话，用中文）
- riskSummary: 风险评估和影响（1-2 句话，用中文）
- actionSummary: 推荐的行动（2-3 个要点，用中文数组格式）

要求：具体、可操作、专业。"""

        try:
            result = await self._call_api(
                [{"role": "user", "content": prompt}],
                response_format="json_object",
            )

            return LLMRecommendation(
                reason=result.get("reason", ""),
                risk_summary=result.get("riskSummary", ""),
                action_summary=result.get("actionSummary", ""),
                meta={
                    "llmUsed": True,
                    "provider": "openai",
                    "model": self.model,
                },
            )
        except Exception as e:
            # Fallback to template on error
            raise RuntimeError(f"LLM API call failed: {str(e)}") from e

    async def generate_report_narrative(
        self, report_data: dict[str, Any]
    ) -> LLMReportNarrative:
        """Generate report narrative using LLM."""
        report_type = report_data.get("type", "daily")
        stats = report_data.get("stats", {})

        prompt = f"""你是实验室管理系统的 AI 助手。请为 {report_type} 报告生成叙述性摘要：

统计数据:
{json.dumps(stats, indent=2)}

请提供 JSON 格式的响应，包含：
- summary: 报告的总体摘要（2-3 句话，用中文）
- highlights: 3-5 个关键亮点或值得注意的项目列表（用中文数组）

要求：简洁、基于事实、突出重要趋势或问题。"""

        try:
            result = await self._call_api(
                [{"role": "user", "content": prompt}],
                response_format="json_object",
            )

            return LLMReportNarrative(
                summary=result.get("summary", ""),
                highlights=result.get("highlights", []),
                meta={
                    "llmUsed": True,
                    "provider": "openai",
                    "model": self.model,
                },
            )
        except Exception as e:
            raise RuntimeError(f"LLM API call failed: {str(e)}") from e

    async def generate_suggestions(
        self, retrospective_data: dict[str, Any]
    ) -> list[str]:
        """Generate optimization suggestions using LLM."""
        patterns = retrospective_data.get("patterns", {})

        prompt = f"""你是实验室管理系统的 AI 助手。基于以下执行模式，生成 3-5 个具体、可操作的优化建议：

模式:
{json.dumps(patterns, indent=2)}

请提供 JSON 格式的响应，包含：
- suggestions: 3-5 个具体、可操作的建议数组（用中文）

要求：专注于可以实施的实际改进。"""

        try:
            result = await self._call_api(
                [{"role": "user", "content": prompt}],
                response_format="json_object",
            )

            return result.get("suggestions", [])
        except Exception as e:
            raise RuntimeError(f"LLM API call failed: {str(e)}") from e

    async def close(self):
        """Close the HTTP client."""
        await self.client.aclose()


class DisabledLLMService(LLMService):
    """Fallback LLM service that returns template-based responses.

    This service is used when LLM is disabled or unavailable.
    """

    async def generate_recommendation(
        self, event: dict[str, Any], context: dict[str, Any]
    ) -> LLMRecommendation:
        """Generate template-based recommendation."""
        event_type = event.get("type", "unknown")
        source_name = event.get("sourceName", "Unknown")
        risk_level = event.get("riskLevel", "medium")

        # Template-based responses
        templates = {
            "low_stock": {
                "reason": f"化学品 {source_name} 已低于最低库存阈值。需要立即补货以维持实验室运营。",
                "risk_summary": f"风险级别为 {risk_level}。库存不足可能延误实验和研究活动。",
                "action_summary": "审查当前库存水平，验证最低阈值设置，并准备补货申请以供审批。",
            },
            "maintenance_overdue": {
                "reason": f"设备 {source_name} 已超过计划维护窗口。定期维护对设备可靠性和安全性至关重要。",
                "risk_summary": f"风险级别为 {risk_level}。逾期维护可能导致设备故障或安全事故。",
                "action_summary": "立即安排维护，验证设备状态，并记录任何观察到的问题。",
            },
            "equipment_fault": {
                "reason": f"设备 {source_name} 已被标记为异常状态。这需要立即审查以防止安全事故或数据完整性问题。",
                "risk_summary": f"风险级别为 {risk_level}。设备故障可能影响实验结果或构成安全风险。",
                "action_summary": "必要时隔离设备，进行彻底检查，并记录发现以供主管审查。",
            },
        }

        template = templates.get(
            event_type,
            {
                "reason": f"检测到 {source_name} 的事件。需要审查。",
                "risk_summary": f"风险级别为 {risk_level}。",
                "action_summary": "审查事件详情并采取适当行动。",
            },
        )

        return LLMRecommendation(
            reason=template["reason"],
            risk_summary=template["risk_summary"],
            action_summary=template["action_summary"],
            meta={
                "llmUsed": False,
                "fallbackReason": "LLM 已禁用或不可用",
            },
        )

    async def generate_report_narrative(
        self, report_data: dict[str, Any]
    ) -> LLMReportNarrative:
        """Generate template-based report narrative."""
        report_type = report_data.get("type", "daily")
        stats = report_data.get("stats", {})

        summary = f"此 {report_type} 报告总结了实验室活动和 AI 员工的行动。"
        highlights = [
            f"总任务数: {stats.get('totalTasks', 0)}",
            f"已完成任务: {stats.get('completedTasks', 0)}",
            f"待审批: {stats.get('pendingApprovals', 0)}",
        ]

        return LLMReportNarrative(
            summary=summary,
            highlights=highlights,
            meta={
                "llmUsed": False,
                "fallbackReason": "LLM 已禁用或不可用",
            },
        )

    async def generate_suggestions(
        self, retrospective_data: dict[str, Any]
    ) -> list[str]:
        """Generate template-based suggestions."""
        return [
            "审查任务完成率并识别瓶颈",
            "分析审批拒绝模式以提高任务质量",
            "监控设备维护计划以防止逾期项目",
            "根据使用模式优化库存阈值",
        ]


__all__ = [
    "LLMService",
    "LLMRecommendation",
    "LLMReportNarrative",
    "OpenAICompatibleLLMService",
    "DisabledLLMService",
]
